### ISSUE TITLE
CSS Changes

### ISSUE THREAD

**Issue by shinson** [codefordc/dc-campaign-finance-watch#18]
To change the title Font

``` css
core-toolbar {
    background-color: #03A9F4;
    font-size: 3.3 em;
}
```

To put in a max width for the chart. though this might have to change according how the graph is changed. 

``` css
#container {
    max-width:800px;
}
```
